{
 "title": "System and Process",
 "description": "Shows metrics for system and selected processes.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "System: {{instance}}"
    },
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "System: {{instance}}"
    },
    {
     "expr": "100 * sum by (instance, process) (rate(windows_process_cpu_time_total[$__rate_interval]))\r\n  / on(instance) group_left\r\n    windows_cpu_info_logical_processor",
     "legendFormat": "{{process}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes - windows_memory_physical_free_bytes",
     "legendFormat": "System-Memory: {{instance}}"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "System-Memory: {{instance}}"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "System-Swap: {{instance}}"
    },
    {
     "expr": "windows_process_working_set_private_bytes",
     "legendFormat": "PrivateWorkingSet: {{process}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk: System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_physical_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "Read: Disk {{disk}} - {{instance}}"
    },
    {
     "expr": "rate(windows_physical_disk_write_bytes_total[$__rate_interval])",
     "legendFormat": "Write: Disk {{disk}} - {{instance}}"
    },
    {
     "expr": "rate(windows_physical_disk_read_bytes_total[$__rate_interval]) + rate(windows_physical_disk_write_bytes_total[$__rate_interval])",
     "legendFormat": "Total: Disk {{disk}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network: System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[$__rate_interval])",
     "legendFormat": "Read: NIC {{nic}} - {{instance}}"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total[$__rate_interval])",
     "legendFormat": "Write: NIC {{nic}} - {{instance}}"
    },
    {
     "expr": "rate(windows_net_bytes_total[$__rate_interval])",
     "legendFormat": "Total: NIC {{nic}} - {{instance}}"
    }
   ]
  }
 ]
}