collectors:
  enabled: cpu,logical_disk,memory,net,os,physical_disk,service,system,cpu_info,process
collector:
  service:
    include: "windows_exporter"
  process:
  # Regex is case sensitive
  # e.g. If you set "AppName" use "AppName" matches but "appname" does not match
  # Add your process names from Windows.TaskManager separated by |
    include: "(CompanyName.AppName|prometheus|grafana|windows_exporter|MatrixCE.MgmtServer|MatrixCE.RecServer).*"
log:
  level: warn
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
web:
  listen-address: ":9182"